"""Contract tests for LEG-041 — CompositeAgent fan-out/fan-in over native beaver.

The unified composite (LEG-040/LEG-044) fans out each branch to the child class's
inbox with ``level + 1`` and ``current_index = 0``, keeping the SAME ``task_id`` —
the task id is the task's identity and never changes anywhere in the flow,
including across a fan-out. Each branch carries an **autogenerated ``branch_id``**
(uuid4 — distinct per branch at this level of the same task, constant along the
branch's sequence, preserved through the branch's whole execution) that names its
join slot. The join bookkeeping is keyed directly on the constant ``task_id``
(O(1) fetch; no child→parent scan). On all-complete it groups the branch
results **by slot** (the autogenerated ``branch_id`` — collision-free even when
two leaves share the same ``output_as``) and hands that grouped mapping to the
pattern's own `build_output_as` (no generic engine default: output construction
is the pattern's model), then decrements ``level`` (−1) and resumes its own
level (Schema 2 §12.4). Nothing waits and nothing is locked:
branches run as soon as their deposit lands on their queue (release parallelism,
rule 8).
"""

from __future__ import annotations

import pytest
from beaver import AsyncBeaverDB

from legio.agents.base import AgentBase
from legio.agents.composite_agent import CompositeAgent
from legio.flow import (
    ExecutionRequestMessage,
    ExecutionResultMessage,
    build_payload,
)
from legio.naming import gathering_key, queue_key


class Branch(AgentBase):
    """An atomic branch: reads its input under ``input_as`` and constructs its
    output under ``output_as``."""

    def __init__(self, *, key: str, input_as: str, output_as: str, **kwargs: object) -> None:
        self._key = key
        self._input_as = input_as
        super().__init__(**kwargs, output_as=output_as)  # type: ignore[call-arg]

    async def _handle(self, request: ExecutionRequestMessage) -> dict:
        inp = request.payload.get(self._input_as, {})
        return build_payload({self._key: inp.get("seed", 0)}, output_as=self._output_as)


async def pop_one(db: AsyncBeaverDB, agent_id: str) -> dict | None:
    try:
        item = await db.queue(queue_key(agent_id)).get(block=False)
    except IndexError:
        return None
    return item.data


class GatherComposite(CompositeAgent):
    """A concrete composite pattern: transcribes each branch's built payload
    (slot order) into its own ``output_as``.

    The engine's ``CompositeAgent`` has **no** generic default build — output
    construction is the pattern's model (it must satisfy the pattern's declared
    ``output_schema``). This fictitious-domain pattern picks the gather/
    transcription composition for its declared shape.
    """

    async def build_output_as(self, info):
        gathered: dict = {}
        for payload in info.values():
            gathered.update(payload)
        return build_payload(gathered, output_as=self._output_as)


class SlottedComposite(CompositeAgent):
    """A concrete composite pattern that keeps each branch's slot separate.

    It exposes every branch's built payload under a positional key (fan-out
    order) instead of transcribing keys — so two branches that end in agents
    sharing the same ``output_as`` are both visible, never colliding.
    """

    async def build_output_as(self, info):
        slotted = {str(index): dict(payload) for index, payload in enumerate(info.values())}
        return build_payload(slotted, output_as=self._output_as)


class BreakingComposite(CompositeAgent):
    """A broken concrete composite whose build model raises (a misbehaving
    pattern) — the failure must surface visibly through the composite's own
    context, never as a silent loop."""

    async def build_output_as(self, info):
        raise ValueError("boom build")


def build_composite(
    *,
    db: AsyncBeaverDB,
    branches,
    agent_id: str = "comp",
    input_as: str = "main",
    output_as: str = "comp",
    composite_cls: type[CompositeAgent] = GatherComposite,
) -> CompositeAgent:
    # ``branches`` is a list of single-step (class, input_as) branches; the
    # CompositeAgent expects each branch to be a *route* (list of steps), so we
    # wrap each in a one-step route.
    routes: list[list[tuple[str, str]]] = [[branch] for branch in branches]
    return composite_cls(
        agent_id=agent_id, db=db, branches=routes, input_as=input_as, output_as=output_as
    )


def composite_request(
    *,
    task_id: str,
    payload: dict,
    route: tuple[tuple[str, str], ...],
    current_index: int,
    end_of_level_queue: str,
    level: int = 1,
) -> ExecutionRequestMessage:
    return ExecutionRequestMessage(
        level_route=route,
        current_index=current_index,
        end_of_level_queue=end_of_level_queue,
        level=level,
        launcher_class=route[0][0] if route else "",
        task_id=task_id,
        payload=payload,
    )


async def fan_out_and_collect(
    *, db: AsyncBeaverDB, comp: CompositeAgent, request: ExecutionRequestMessage
) -> list[ExecutionRequestMessage]:
    """Deposit a request on the composite, run one dispatch, and read back each
    fanned-out child (keeping fan-out order). Returns the child messages."""
    await db.queue(queue_key(comp._agent_id)).put(request.model_dump(mode="json"), priority=0.0)
    assert await comp.process_next() is True
    children: list[ExecutionRequestMessage] = []
    for route in comp._branches:
        branch_class = route[0][0]
        item = await pop_one(db, branch_class)
        assert item is not None
        children.append(ExecutionRequestMessage.model_validate(item))
    return children


def child_result(
    *,
    branch_id: str,
    level_route: tuple[tuple[str, str], ...],
    task_id: str,
    payload: dict,
    level: int = 2,
    current_index: int = 0,
) -> ExecutionResultMessage:
    """Build a branch's returning result carrying the parent-assigned branch_id."""
    return ExecutionResultMessage(
        level_route=level_route,
        current_index=current_index,
        end_of_level_queue=gathering_key("comp"),
        level=level,
        launcher_class="main",
        task_id=task_id,
        branch_id=branch_id,
        payload=payload,
    )


@pytest.mark.asyncio
async def test_composite_fans_out_both_branches_sharing_task_id(
    beaver_db: AsyncBeaverDB,
) -> None:
    """Both branches get a request (current_index 0, level+1) that keep the task
    id — the task id never changes in the flow (release parallelism). Each branch
    gets an autogenerated branch_id, distinct per branch of the same task."""
    comp = build_composite(db=beaver_db, branches=[("b1", "b1"), ("b2", "b2")])
    request = composite_request(
        task_id="P-root",
        payload={"main": {"seed": 9}},
        route=(("main", "main"), ("comp", "comp")),
        current_index=1,
        end_of_level_queue="result:P-root",
    )
    children = await fan_out_and_collect(db=beaver_db, comp=comp, request=request)
    r1, r2 = children[0], children[1]

    # both branches fanned out: current_index 0, one level deeper
    assert r1.current_index == 0 and r2.current_index == 0
    assert r1.level == 2 and r2.level == 2
    # branches return to the composite's own gathering queue (gather:comp),
    # its second physical queue — never onto its class inbox
    assert r1.end_of_level_queue == gathering_key("comp")
    assert r2.end_of_level_queue == gathering_key("comp")
    # the task id stays constant across the fan-out — it is the task's identity
    assert r1.task_id == "P-root"
    assert r2.task_id == "P-root"
    # the shared input is re-keyed under each branch's own input_as
    assert r1.payload == {"b1": {"seed": 9}}
    assert r2.payload == {"b2": {"seed": 9}}
    # each branch has an autogenerated, distinct branch_id (the join slot)
    assert r1.branch_id
    assert r2.branch_id
    assert r1.branch_id != r2.branch_id


@pytest.mark.asyncio
async def test_composite_two_same_class_branches_get_distinct_branch_ids(
    beaver_db: AsyncBeaverDB,
) -> None:
    """Two branches of the very same class in one task are one task with
    two distinct join slots — their autogenerated branch_ids differ, so they do
    not collide on join (the very case a class-name slot identity would break)."""
    comp = build_composite(db=beaver_db, branches=[("same", "same"), ("same", "same")])
    request = composite_request(
        task_id="P-same",
        payload={"main": {"seed": 5}},
        route=(("main", "main"), ("comp", "comp")),
        current_index=1,
        end_of_level_queue="result:P-same",
    )
    children = await fan_out_and_collect(db=beaver_db, comp=comp, request=request)
    a, b = children[0], children[1]
    assert a.branch_id != b.branch_id
    # both land on the same child class queue, yet are distinct slots of one task
    assert a.task_id == b.task_id == "P-same"


@pytest.mark.asyncio
async def test_composite_does_not_fan_out_a_branch_into_a_closed_gate(
    beaver_db: AsyncBeaverDB,
) -> None:
    """§12.5.1/§12.5.5: a branch deposit into a disabled class is blocked.

    The blocked branch is NOT delivered (nothing enters a non-enabled class via
    fan-in); its join slot records a visible ``error`` result (rule 9) so the
    fan-in still completes and the composite surfaces the failure — never a
    silent drop and never a corrupted join.
    """
    await beaver_db.dict("gates").set("b2", {"state": "disabled"})
    comp = build_composite(db=beaver_db, branches=[("b1", "b1"), ("b2", "b2")])
    request = composite_request(
        task_id="P-gate",
        payload={"main": {"seed": 1}},
        route=(("main", "main"), ("comp", "comp")),
        current_index=1,
        end_of_level_queue="result:P-gate",
    )
    await beaver_db.queue(queue_key("comp")).put(request.model_dump(mode="json"), priority=0.0)
    assert await comp.process_next() is True

    # the open branch was delivered; the closed one was not
    assert await pop_one(beaver_db, "b1") is not None
    assert await pop_one(beaver_db, "b2") is None

    # the blocked branch's slot carries a visible error — the fan-in sees it
    state = await beaver_db.dict("state:composite:comp").fetch("P-gate")
    assert state is not None
    assert len(state["expected"]) == 2
    slots = beaver_db.dict("state:composite:comp:slots")
    errored = []
    for branch_id in state["expected"]:
        slot = await slots.fetch(f"P-gate:{branch_id}")
        assert slot is not None
        if slot["result"] is not None:
            errored.append(slot["result"])
    assert len(errored) == 1
    assert "disabled" in errored[0]["error"]


@pytest.mark.asyncio
async def test_composite_does_not_advance_until_all_branches_return(
    beaver_db: AsyncBeaverDB,
) -> None:
    """After fan-out the composite has not advanced; only when ALL branches
    return (joined) does it resume its own level."""
    comp = build_composite(db=beaver_db, branches=[("b1", "b1"), ("b2", "b2")])
    request = composite_request(
        task_id="P-partial",
        payload={"main": {"seed": 1}},
        route=(("main", "main"), ("comp", "comp"), ("after", "after")),
        current_index=1,
        end_of_level_queue="result:P-partial",
    )
    children = await fan_out_and_collect(db=beaver_db, comp=comp, request=request)
    child1, child2 = children[0], children[1]

    # One branch returns; the other has not. The composite must NOT advance yet.
    await beaver_db.queue(queue_key(gathering_key("comp"))).put(
        child_result(
            branch_id=child1.branch_id,
            level_route=(("b1", "b1"),),
            task_id="P-partial",
            payload={"b1": 1},
        ).model_dump(mode="json"),
        priority=0.0,
    )
    # process_next dispatches the result; no "after" deposit yet
    assert await comp.process_next() is True
    assert await pop_one(beaver_db, "after") is None

    # Second branch returns -> now the join completes and the composite advances.
    await beaver_db.queue(queue_key(gathering_key("comp"))).put(
        child_result(
            branch_id=child2.branch_id,
            level_route=(("b2", "b2"),),
            task_id="P-partial",
            payload={"b2": 2},
        ).model_dump(mode="json"),
        priority=0.0,
    )
    assert await comp.process_next() is True
    advanced = await pop_one(beaver_db, "after")
    assert advanced is not None
    adv = ExecutionRequestMessage.model_validate(advanced)
    assert adv.current_index == 2
    assert adv.level == 1
    assert adv.task_id == "P-partial"
    assert adv.payload == {"after": {"b1": 1, "b2": 2}}


@pytest.mark.asyncio
async def test_composite_joins_and_delivers_to_flow_end(
    beaver_db: AsyncBeaverDB,
) -> None:
    """A multi-branch composite that is the last step of level 1 delivers the
    final result to the final-result queue on all-complete."""
    comp = build_composite(db=beaver_db, branches=[("b1", "b1"), ("b2", "b2")])
    request = composite_request(
        task_id="P-end",
        payload={"main": {"seed": 4}},
        route=(("main", "main"), ("comp", "comp")),
        current_index=1,
        end_of_level_queue="result:P-end",
    )
    children = await fan_out_and_collect(db=beaver_db, comp=comp, request=request)

    for child, branch_name in ((children[0], "b1"), (children[1], "b2")):
        await beaver_db.queue(queue_key(gathering_key("comp"))).put(
            child_result(
                branch_id=child.branch_id,
                level_route=((branch_name, branch_name),),
                task_id="P-end",
                payload={branch_name: 4},
            ).model_dump(mode="json"),
            priority=0.0,
        )
    await comp.process_next()
    await comp.process_next()

    result_item = await pop_one(beaver_db, "result:P-end")
    assert result_item is not None
    result = ExecutionResultMessage.model_validate(result_item)
    assert result.task_id == "P-end"
    assert result.payload == {"comp": {"b1": 4, "b2": 4}}


@pytest.mark.asyncio
async def test_composite_slots_never_collide_on_shared_output_as(
    beaver_db: AsyncBeaverDB,
) -> None:
    """Two branches ending in agents with the **same** ``output_as`` do not
    collide on join: each result stays in its own autogenerated ``branch_id``
    slot, so the pattern's `build_output_as` receives both values separately."""
    # Both branch leaves build their value under the same key "x" — the case a
    # flat key-union would collapse (the last result would overwrite the first).
    comp = build_composite(
        db=beaver_db, branches=[("same", "same"), ("same", "same")], composite_cls=SlottedComposite
    )
    request = composite_request(
        task_id="P-collide",
        payload={"main": {"seed": 9}},
        route=(("main", "main"), ("comp", "comp")),
        current_index=1,
        end_of_level_queue="result:P-collide",
    )
    children = await fan_out_and_collect(db=beaver_db, comp=comp, request=request)
    a, b = children[0], children[1]

    # Both branches return their value under the very same output_as key "same".
    await beaver_db.queue(queue_key(gathering_key("comp"))).put(
        child_result(
            branch_id=a.branch_id,
            level_route=(("same", "same"),),
            task_id="P-collide",
            payload={"same": {"x": 1}},
        ).model_dump(mode="json"),
        priority=0.0,
    )
    await beaver_db.queue(queue_key(gathering_key("comp"))).put(
        child_result(
            branch_id=b.branch_id,
            level_route=(("same", "same"),),
            task_id="P-collide",
            payload={"same": {"x": 2}},
        ).model_dump(mode="json"),
        priority=0.0,
    )
    assert await comp.process_next() is True
    assert await comp.process_next() is True

    result_item = await pop_one(beaver_db, "result:P-collide")
    assert result_item is not None
    result = ExecutionResultMessage.model_validate(result_item)
    assert result.task_id == "P-collide"
    # Both values survived, keyed by fan-out position — nothing overwrote anything.
    assert result.payload == {"comp": {"0": {"same": {"x": 1}}, "1": {"same": {"x": 2}}}}


@pytest.mark.asyncio
async def test_composite_build_failure_surfaces_via_own_context(
    beaver_db: AsyncBeaverDB,
) -> None:
    """A composite whose build model raises surfaces a visible error through the
    composite's own continuation — never mis-routed via a child's context and
    never re-deposited onto its own gathering queue (no silent busy loop)."""
    comp = build_composite(db=beaver_db, branches=[("b1", "b1")], composite_cls=BreakingComposite)
    request = composite_request(
        task_id="P-broken",
        payload={"main": {"seed": 1}},
        route=(("main", "main"), ("comp", "comp")),
        current_index=1,
        end_of_level_queue="result:P-broken",
    )
    children = await fan_out_and_collect(db=beaver_db, comp=comp, request=request)

    await beaver_db.queue(queue_key(gathering_key("comp"))).put(
        child_result(
            branch_id=children[0].branch_id,
            level_route=(("b1", "b1"),),
            task_id="P-broken",
            payload={"b1": 1},
        ).model_dump(mode="json"),
        priority=0.0,
    )
    assert await comp.process_next() is True

    # The error lands on the composite's closer (its own resumed level) and the
    # gathering queue is not re-fed: the join is closed exactly once.
    result_item = await pop_one(beaver_db, "result:P-broken")
    assert result_item is not None
    result = ExecutionResultMessage.model_validate(result_item)
    assert result.task_id == "P-broken"
    assert "error" in result.payload
    assert await pop_one(beaver_db, gathering_key("comp")) is None
    assert await pop_one(beaver_db, "b1") is None


@pytest.mark.asyncio
async def test_composite_joins_a_multi_step_branch_by_branch_id(
    beaver_db: AsyncBeaverDB,
) -> None:
    """A composite (multi-step) branch returns with an expanded ``level_route``
    whose first element is the branch's first *step*, not the branch class. The
    composite must still slot it correctly via the preserved autogenerated
    ``branch_id`` the parent assigned at fan-out (LEG-041 branch_id schema field).
    """
    comp = build_composite(
        db=beaver_db, branches=[("seqbranch", "seqbranch"), ("atomic", "atomic")]
    )
    request = composite_request(
        task_id="P-branchy",
        payload={"main": {"seed": 3}},
        route=(("main", "main"), ("comp", "comp"), ("after", "after")),
        current_index=1,
        end_of_level_queue="result:P-branchy",
    )
    children = await fan_out_and_collect(db=beaver_db, comp=comp, request=request)
    seq_branch, atomic_branch = children[0], children[1]

    # The multi-step branch ('seqbranch') returns with the expanded level_route
    # (("summ_a", ...), ("summ_b", ...)) but keeps the parent-assigned branch_id.
    await beaver_db.queue(queue_key(gathering_key("comp"))).put(
        child_result(
            branch_id=seq_branch.branch_id,
            level_route=(("summ_a", "summ_a"), ("summ_b", "summ_b")),
            task_id="P-branchy",
            payload={"seq": "ok"},
            current_index=1,
        ).model_dump(mode="json"),
        priority=0.0,
    )
    assert await comp.process_next() is True

    # Second (atomic) branch still returns with its own branch_id.
    await beaver_db.queue(queue_key(gathering_key("comp"))).put(
        child_result(
            branch_id=atomic_branch.branch_id,
            level_route=(("atomic", "atomic"),),
            task_id="P-branchy",
            payload={"at": 1},
        ).model_dump(mode="json"),
        priority=0.0,
    )
    assert await comp.process_next() is True

    advanced = await pop_one(beaver_db, "after")
    assert advanced is not None
    adv = ExecutionRequestMessage.model_validate(advanced)
    assert adv.current_index == 2
    assert adv.level == 1
    assert adv.task_id == "P-branchy"
    assert adv.payload == {"after": {"seq": "ok", "at": 1}}


@pytest.mark.asyncio
async def test_composite_resume_preserves_its_own_branch_id(
    beaver_db: AsyncBeaverDB,
) -> None:
    """A composite nested as a branch of an outer composite must resume its own
    level carrying the outer-assigned ``branch_id``, so that when it later closes
    to the outer gathering queue the outer fan-in still slots it correctly."""
    comp = build_composite(db=beaver_db, branches=[("b1", "b1"), ("b2", "b2")])
    # Incoming request arrived as a branch of an outer composite -> branch_id set
    # (autogenerated by the outer composite at fan-out).
    request = composite_request(
        task_id="P-nested",
        payload={"main": {"seed": 1}},
        route=(("main", "main"), ("comp", "comp"), ("after", "after")),
        current_index=1,
        end_of_level_queue="result:P-nested",
        level=2,
    )
    outer_branch_id = "P-nested:outer:0"
    await beaver_db.queue(queue_key("comp")).put(
        request.model_dump(mode="json") | {"branch_id": outer_branch_id},
        priority=0.0,
    )
    assert await comp.process_next() is True
    children = []
    for route in comp._branches:
        branch_class = route[0][0]
        item = await pop_one(beaver_db, branch_class)
        assert item is not None
        children.append(ExecutionRequestMessage.model_validate(item))

    # Both this inner composite's branches return with their own autogenerated ids.
    for child, route in zip(children, comp._branches):
        branch_class = route[0][0]
        await beaver_db.queue(queue_key(gathering_key("comp"))).put(
            child_result(
                branch_id=child.branch_id,
                level_route=route,
                task_id="P-nested",
                payload={branch_class: 1},
                level=3,
            ).model_dump(mode="json"),
            priority=0.0,
        )
        assert await comp.process_next() is True

    # The resumed advance must carry the outer branch_id, NOT an empty value.
    advanced = await pop_one(beaver_db, "after")
    assert advanced is not None
    adv = ExecutionRequestMessage.model_validate(advanced)
    assert adv.current_index == 2
    assert adv.task_id == "P-nested"
    assert adv.branch_id == outer_branch_id


@pytest.mark.asyncio
async def test_composite_with_no_branches_fails_visibly(beaver_db: AsyncBeaverDB) -> None:
    """A composite with no branches is a construction error, never silent
    (rule 9)."""
    comp = build_composite(db=beaver_db, branches=[])
    request = composite_request(
        task_id="P-empty",
        payload={},
        route=(("comp", "comp"),),
        current_index=0,
        end_of_level_queue="result:P-empty",
    )
    await beaver_db.queue(queue_key("comp")).put(request.model_dump(mode="json"), priority=0.0)

    await comp.process_next()

    result_item = await pop_one(beaver_db, "result:P-empty")
    assert result_item is not None
    result = ExecutionResultMessage.model_validate(result_item)
    assert result.task_id == "P-empty"
    assert "error" in result.payload
