"""`legio.agents.composite_agent` — the unified composite runner (LEG-040/LEG-044).

A composite (`type: composite` + `branches`, AGENT_LIFECYCLE §4.10/§4.11) has
**one** runner that handles every arity uniformly: a composite with a single
branch (a sequence) and one with several branches (a parallel) are the same
agent, the same code path.

A composite consumes **two physical queues** (§12.2/§12.3): its class inbox
(``legio:queue:<class>``, only entry requests) and its own **gathering queue**
(``legio:queue:gather:<agent_id>``, only fan-in results). Messages are
partitioned by queue, never by message type, so there is no dispatch on
``message_type`` anywhere. Its ``process_next`` is the two-cycle poll:

1. **Intake (unconditional)** — poll the class inbox; every entry request is
   fanned out and its task annotated as pending.
2. **Collection (gated)** — only when at least one task is pending is the
   gathering queue polled; with none pending there is nothing legitimate to
   receive, and a result that lands anyway is an anomaly surfaced as a visible
   error (rule 9), never silently processed or re-deposited.

- **Fan-out** (inbox, intake): for each branch the composite deposits that
  branch's **loader-resolved `level_route`** — its `(class, input_as)` steps —
  with `current_index = 0`, `end_of_level_queue` = this composite's gathering
  queue (``gather:<agent_id>``), `level + 1`, the SAME `task_id`, and a
  **fresh autogenerated `branch_id`** (uuid4 — no parent-derived naming,
  distinct from its own and from every other branch across all levels, constant
  along the branch's sequence). It re-keys its shared `input_as` under each
  branch's first step's `input_as` (§12.1). A step whose name references a
  `type: composite` agent stays as a position in the branch's route: that
  composite is invoked like any capability agent through its inbox and performs
  its own fan-out recursively (reuse by reference).
- **Fan-in** (gathering, collection): the result's `branch_id` names the join
  slot; its `task_id` is the join key (direct fetch, no scan). The composite
  accounts for fan-in one result per `branch_id`, conserving it across a
  multi-step branch (whose returned `level_route` expands to its own steps) and
  across failures (an `error` result, rule 9). The join completes when every
  branch_id of the task is present.
- **Build + resume**: on fan-in completion the composite **groups the branch
  results collision-free** — each branch's built payload ``{output_as: value}``
  stays under its own autogenerated ``branch_id`` slot (distinct per branch of
  the task, so two leaves sharing the same ``output_as`` never collide) — and
  hands that grouped mapping to the re-implementable seam ``build_output_as``.
  The composite has **no generic default build**: constructing ``output_as``
  from the branch slots is the pattern's own model (it must satisfy the
  pattern's declared ``output_schema`` — superset-verified here, rule 12), so a
  concrete composite inherits and implements it. Then it decrements ``level``
  (−1) and resumes its own level through the uniform Schema 2 advance, with the
  ``end_of_level_queue`` its creator supplied.

Nothing waits and nothing is locked (rule 8): branches run as soon as their
deposit lands on their queue; the join is bookkeeping, not polling-blocking;
the collection cycle is **gated by pending bookkeeping**, never a blind poll.
Each branch deposit reads the target class's gate (§12.5): a disabled class
blocks the branch deposit at fan-out (§12.5.5 — the slot records a visible
``error`` result so the fan-in still completes and the composite surfaces the
failure, never a silent drop). Errors are never silent (rule 9).
"""

from __future__ import annotations

import logging
import uuid
from collections.abc import Mapping, Sequence
from typing import Any

from legio.agents.base import AgentBase
from legio.concurrency import ShutdownGate
from legio.flow import ExecutionRequestMessage, ExecutionResultMessage
from legio.naming import gathering_key, queue_key

logger = logging.getLogger(__name__)

# Each composite class keeps its in-flight join continuation here, keyed by the
# TASK id (constant across the flow). Multiple concurrent tasks simply occupy
# several keys.
_STATE_SCOPE = "state:composite"


class CompositeAgent(AgentBase):
    """The unified composite runner: ramify to branches, gather, build."""

    def __init__(
        self,
        *,
        agent_id: str,
        db: Any,
        branches: Sequence[Sequence[tuple[str, str]]],
        input_as: str = "",
        output_as: str = "",
        input_schema: Mapping[str, Any] | None = None,
        output_schema: Mapping[str, Any] | None = None,
        drain: ShutdownGate | None = None,
    ) -> None:
        super().__init__(
            agent_id=agent_id,
            db=db,
            output_as=output_as,
            input_schema=input_schema,
            output_schema=output_schema,
            drain=drain,
        )
        # Each branch is a route of (class, input_as) — the branch's own
        # loader-resolved steps (re-keying info, §12.1).
        self._branches: list[tuple[tuple[str, str], ...]] = [tuple(branch) for branch in branches]
        self._input_as = input_as
        self._state = db.dict(f"{_STATE_SCOPE}:{agent_id}")
        # The composite's second physical queue (§12.3): its branches return
        # their fan-in results here, partitioned by queue — never onto the
        # class inbox, never by message-type dispatch.
        self._gather_name = gathering_key(agent_id)
        self._gather_queue = db.queue(queue_key(self._gather_name))

    async def process_next(self) -> bool:
        """The composite's two-inlet poll: intake + gated collection (§12.3).

        - **Intake (unconditional):** polls the class inbox; every entry
          request is fanned out and its task annotated as pending.
        - **Collection (gated):** only when at least one task is pending is the
          gathering queue polled — with none pending there is nothing
          legitimate to receive, so the poll is pointless; a message that
          arrived anyway is an anomaly surfaced as a visible error (rule 9).
        """
        handled = False
        if self._drain_holding():
            return False
        try:
            inbox_item = await self._queue.get(block=False)
        except IndexError:
            pass
        else:
            await self._process_inbox_item(dict(inbox_item.data))
            handled = True

        if await self._has_pending():
            try:
                gather_item = await self._gather_queue.get(block=False)
            except IndexError:
                pass
            else:
                await self._process_join_item(dict(gather_item.data))
                handled = True
        return handled

    async def _has_pending(self) -> bool:
        """Whether any fanned-out task is still waiting on its fan-in (the gate).

        The pending set is the composite's own bookkeeping: one record per task
        (``state:<composite>`` keyed by ``task_id``) exists from fan-out until
        that task's join completes and the record is deleted. It is the gate of
        the collection cycle: with none pending, no flow can legitimately
        deliver anything to the gathering queue (§12.3).
        """
        try:
            return await self._state.count() > 0
        except Exception:
            logger.exception("composite pending check failed agent=%s", self._agent_id)
            raise

    async def _process_join_item(self, item: dict[str, Any]) -> None:
        """Consume one item from the gathering queue (a fan-in result) and join.

        The gathering queue carries only branch returns (§12.3). A result
        landing there with no pending fan-out, or naming an unknown
        ``task_id``/``branch_id``, is an anomaly — surfaced visibly (rule 9)
        and never re-deposited, so it can never re-feed the gathering queue
        into a silent loop.
        """
        try:
            result = ExecutionResultMessage.model_validate(item)
            logger.info(
                "composite collect agent=%s task=%s branch=%s",
                self._agent_id,
                result.task_id,
                result.branch_id,
            )
            await self._fan_in(result)
        except Exception:
            logger.exception(
                "composite join failed agent=%s task=%s",
                self._agent_id,
                item.get("task_id", "?"),
            )
            raise

    async def _handle(self, request: ExecutionRequestMessage) -> dict[str, Any] | None:
        """The inbox dispatch: every entry request fans out (its job is the
        fan-in, which arrives on the separate gathering queue — §12.3)."""
        await self._fan_out(request)
        return None

    async def _fan_out(self, request: ExecutionRequestMessage) -> None:
        """Deposit one request per branch with its own expanded route."""
        if not self._branches:
            raise ValueError(f"composite agent {self._agent_id!r} has no branches")

        existing = await self._state.fetch(request.task_id)
        if existing is not None:
            logger.debug(
                "composite already fanned out agent=%s task=%s",
                self._agent_id,
                request.task_id,
            )
            return

        slots: dict[str, dict[str, Any]] = {}
        for index, branch_route in enumerate(self._branches):
            branch_slot = str(uuid.uuid4())
            first_class, first_input_as = branch_route[0]
            if not await self._class_gate_open(first_class):
                logger.warning(
                    "composite branch blocked agent=%s task=%s branch=%s first=%s gate=closed",
                    self._agent_id,
                    request.task_id,
                    index,
                    first_class,
                )
                slots[branch_slot] = {
                    "result": {
                        "error": (
                            f"deposit blocked: branch class {first_class!r} is disabled "
                            f"(gate closed at fan-out, task={request.task_id})"
                        )
                    },
                    "route": branch_route,
                }
                continue
            child = ExecutionRequestMessage(
                level_route=branch_route,
                current_index=0,
                end_of_level_queue=self._gather_name,  # this composite's gathering queue
                level=request.level + 1,
                launcher_class=request.launcher_class,
                task_id=request.task_id,
                branch_id=branch_slot,
                payload=(
                    {first_input_as: request.payload[self._input_as]}
                    if self._input_as and self._input_as in request.payload
                    else dict(request.payload)
                ),
            )
            logger.info(
                "composite fan-out agent=%s task=%s branch=%s first=%s steps=%d level=%s branch_id=%s",
                self._agent_id,
                request.task_id,
                index,
                first_class,
                len(branch_route),
                child.level,
                branch_slot,
            )
            await self._deliver(first_class, child.model_dump(mode="json"))
            slots[branch_slot] = {"result": None, "route": branch_route}

        record = {
            "continuation": {
                "level_route": list(request.level_route),
                "current_index": request.current_index,
                "end_of_level_queue": request.end_of_level_queue,
                "level": request.level,
                "launcher_class": request.launcher_class,
                "task_id": request.task_id,
                "branch_id": request.branch_id,
                "payload": dict(request.payload),
            },
            "slots": slots,
        }
        await self._state.set(request.task_id, record)

    async def _fan_in(self, result: ExecutionResultMessage) -> None:
        """Account for one returned branch; when all are in, build and resume."""
        record = await self._state.fetch(result.task_id)
        if record is None:
            raise ValueError(
                f"composite {self._agent_id!r}: no fan-out for task={result.task_id}"
            )

        branch = result.branch_id or ""
        slot = record["slots"].get(branch)
        if slot is None:
            raise ValueError(
                f"composite {self._agent_id!r}: unknown branch={branch!r} for task={result.task_id}"
            )
        slot["result"] = dict(result.payload)

        if any(s["result"] is None for s in record["slots"].values()):
            logger.debug(
                "composite partial agent=%s task=%s",
                self._agent_id,
                result.task_id,
            )
            await self._state.set(result.task_id, record)
            return

        logger.info("composite joined agent=%s task=%s", self._agent_id, result.task_id)
        # Group the branch results by their slot (the autogenerated branch_id —
        # collision-free even when two leaves share the same output_as) and let
        # the pattern's own build model construct the composite's output.
        branches = {slot_key: dict(slot["result"]) for slot_key, slot in record["slots"].items()}
        try:
            result_payload = await self.build_output_as(branches)
            # Universal output contract: the built value under ``output_as`` is
            # superset-checked against the pattern's declared ``output_schema``
            # before the composite resumes its level (rule 12 + rule 9). A
            # violation is a visible build failure in the composite's own
            # context, never silent.
            self._verify_output_contract(result_payload)
        except Exception as exc:  # noqa: BLE001 - built in the composite's own context
            error = f"{type(exc).__name__}: {exc}"
            logger.warning(
                "composite build failure agent=%s task=%s error=%s",
                self._agent_id,
                result.task_id,
                error,
            )
            result_payload = {"error": error}
        await self._state.delete(result.task_id)
        await self._resume_level(record, result_payload)

    async def build_output_as(self, info: Mapping[str, Mapping[str, Any]]) -> dict[str, Any]:
        """The composite's output build is the pattern's model (no generic default).

        ``info`` groups each branch's built payload by its join slot: the
        autogenerated ``branch_id`` (uuid4), so the grouping **never collides** —
        two leaves ending in agents with the same ``output_as`` occupy distinct
        slots and are both present. Each slot value is the leaf's built payload
        (``{output_as: value}`` or an ``error`` result, rule 9); iteration order
        is fan-out order (the composite's ``branches`` order).

        The engine cannot guess a composition that validates against an arbitrary
        declared ``output_schema``, so there is no default: a concrete composite
        **inherits** ``CompositeAgent`` and implements this to compose the branch
        values into its own ``output_as`` (§12.1 construction).
        """
        raise NotImplementedError

    async def _resume_level(self, record: dict[str, Any], result_payload: dict[str, Any]) -> None:
        """Resume the composite's own level via the uniform Schema 2 advance."""
        cont = record["continuation"]
        route = tuple((step[0], step[1]) for step in cont["level_route"])
        resume = ExecutionRequestMessage(
            level_route=route,
            current_index=cont["current_index"],
            end_of_level_queue=cont["end_of_level_queue"],
            level=cont["level"],
            launcher_class=cont["launcher_class"],
            task_id=cont["task_id"],
            branch_id=cont["branch_id"],
            payload=result_payload,
        )
        await self._route_outcome(resume, result_payload)


__all__ = ["CompositeAgent"]
